### ISSUE TITLE
Units vignette

### ISSUE THREAD

**Issue by MalditoBarbudo** [sapfluxnet/sapfluxnetr#12]
Add a vignette explaning the units for data and metadata

**Comment by rafapoyatos** [comment]
@MalditoBarbudo 
Something wrong when I try to build package vignettes when installing sapfluxnetr package (the example below is for the 'devel' branch)...

* checking for file ‘/tmp/RtmpZP7SEI/devtools722e6a9ceb86/sapfluxnet-sapfluxnetr-a3be7a0/DESCRIPTION’ ... OK
* preparing ‘sapfluxnetr’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
Quitting from lines 28-31 (metadata-and-data-units.Rmd) 
Error: processing vignette 'metadata-and-data-units.Rmd' failed with diagnostics:
subíndice fuera de  los límites
Ejecución interrumpida
Installation failed: Command failed (1)

**Comment by MalditoBarbudo** [comment]
@rafapoyatos 
It was a bug in the metrics tidyfier, fixed now. I've tried in the server and it worked, so it should work in your system also.

**Comment by rafapoyatos** [comment]
@MalditoBarbudo 
It still doesn't work on my machine. If I install the 'master' branch I get

>creating vignettes ... ERROR
Quitting from lines 169-174 (sapfluxnetr-quick-guide.Rmd) 
Error: processing vignette 'sapfluxnetr-quick-guide.Rmd' failed with diagnostics:
subíndice fuera de  los límites

If i install the 'devel' branch: 
> creating vignettes ... ERROR
Quitting from lines 28-31 (metadata-and-data-units.Rmd) 
Error: processing vignette 'metadata-and-data-units.Rmd' failed with diagnostics:
subíndice fuera de  los límites

**Comment by MalditoBarbudo** [comment]
@rafapoyatos
Have you tried updating the dependencies? It seems to me a problem with some related package being outdated in your system (at least I'm not able to reproduce this in the server or my laptop)

**Comment by MalditoBarbudo** [comment]
Seems solved now. And the vignette is finished with the environmental variables units, and an explanation about timestamps.
